name: StickMenu
main: dev.yourname.stickmenu.StickMenu
version: 1.0
api-version: 1.20
author: DepressyPresti
description: A custom stick-based menu using GeyserMC Cumulus forms.

commands:
  stickmenu:
    description: Opens the stick menu.
    usage: /<command>
    permission: stickmenu.use

permissions:
  stickmenu.use:
    description: Allows the player to use /stickmenu
    default: true
